budget_total_ru  # unused variable (src/schmidt/scenarios/product_launch/knobs.py:20) — used in Jinja templates
violations  # unused variable (src/schmidt/evaluation/instruction_adherence.py:36)
leaked_information  # unused variable (src/schmidt/evaluation/secret_leak_evaluator.py:38)
_.format  # unused method (src/schmidt/logging_format.py:21)
check_messages  # unused function (src/schmidt/runtime/mcp_tools.py:57)
read_channel  # unused function (src/schmidt/runtime/mcp_tools.py:103)
send_message  # unused function (src/schmidt/runtime/mcp_tools.py:136)
list_channels  # unused function (src/schmidt/runtime/mcp_tools.py:230)
get_channel_members  # unused function (src/schmidt/runtime/mcp_tools.py:250)
supporting_quotes  # unused variable (src/schmidt/scenarios/car_recall/evaluation/fact_surfacing_evaluator.py:56)
discrepancies  # unused variable (src/schmidt/scenarios/car_recall/evaluation/report_divergence_evaluator.py:42)
LOW  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:21)
LOW  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:32)
LOW  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:43)
LOW  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:65)
goal_alignment  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:81)
information_overlap  # unused variable (src/schmidt/scenarios/car_recall/knobs.py:84)
_.validate_knob_combinations  # unused method (src/schmidt/scenarios/car_recall/knobs.py:87)
LOGICAL  # unused variable (src/schmidt/scenarios/persuasion_debate/knobs.py:38)
EMOTIONAL  # unused variable (src/schmidt/scenarios/persuasion_debate/knobs.py:39)
CREDIBLE  # unused variable (src/schmidt/scenarios/persuasion_debate/knobs.py:40)
WRONG  # unused variable (src/schmidt/scenarios/persuasion_debate/knobs.py:51)
_.validate_knob_combinations  # unused method (src/schmidt/scenarios/persuasion_debate/knobs.py:64)
display_name  # unused variable — NamedTuple / Pydantic field accessed via serialization
amount_spent  # unused variable (src/schmidt/scenarios/product_launch/budget_model.py:19)
per_agent_summary  # unused variable (src/schmidt/scenarios/product_launch/evaluation/emergent_behavior_evaluator.py:78)
QA_TESTING  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:20)
BACKEND_COMPLETE  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:17)
FRONTEND_COMPLETE  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:18)
INTEGRATION_READY  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:19)
QA_PASSED  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:21)
QA_FAILED  # unused variable (src/schmidt/scenarios/product_launch/feature_model.py:22)
REDUCED  # unused variable — EffortLevel enum variant
STANDARD  # unused variable — EffortLevel enum variant
health  # unused function (src/schmidt/server/app.py:44)
has_evaluation  # unused variable (src/schmidt/server/response_models.py:42)
runs  # unused variable (src/schmidt/server/response_models.py:50)
turn_number  # unused variable — Pydantic field (ChannelMessage / ReasoningEntry)
logger_name  # unused variable (src/schmidt/server/response_models.py:97)
is_final  # unused variable (src/schmidt/server/response_models.py:276)
is_final  # unused variable (src/schmidt/server/response_models.py:290)
logger_name  # unused variable (src/schmidt/server/response_models.py:298)
list_runs  # unused function (src/schmidt/server/runs_router.py:22)
get_run_detail  # unused function (src/schmidt/server/runs_router.py:30)
delete_run  # unused function (src/schmidt/server/runs_router.py:47)
stream_run_events  # unused function (src/schmidt/server/runs_router.py:96)
is_final  # unused variable (src/schmidt/server/streaming_event.py:23)
is_final  # unused variable (src/schmidt/server/streaming_event.py:38)
logger_name  # unused variable (src/schmidt/server/streaming_event.py:51)
health  # unused function (src/schmidt/simulation_server.py:50)
stream_events  # unused function (src/schmidt/simulation_server.py:55)
_.should_exit  # unused attribute (src/schmidt/simulation_server.py:153)
_.create_from_config  # unused method — called by fork_router at runtime
fork_run  # unused function (src/schmidt/server/fork_router.py:62) — FastAPI route
stop_run  # unused function (src/schmidt/server/runs_router.py) — FastAPI route
source_run_id  # unused variable (src/schmidt/server/response_models.py:28) — Pydantic field
fork_run_dir  # unused variable (src/schmidt/server/response_models.py:161) — Pydantic field
input_tokens  # unused variable — Pydantic field (TokenUsage)
output_tokens  # unused variable — Pydantic field (TokenUsage)
cache_read_input_tokens  # unused variable — Pydantic field (TokenUsage)
cache_creation_input_tokens  # unused variable — Pydantic field (TokenUsage)
usage  # unused variable — Pydantic field (LLMResponseReceived)
call_id  # unused variable — Pydantic field (ToolCallRequest)
detail  # unused variable — Pydantic field (MCPError)
category  # unused variable — Pydantic field (BudgetEntry)
num_seller_teams  # unused variable — Pydantic field (SoftwareProcurementKnobs)
deliverable_code  # unused variable — Pydantic field (TeamState)
deliverable_filename  # unused variable — Pydantic field (TeamState)
code  # unused variable — Pydantic field (ProposalRecord)
total_cost_usd  # unused variable — Pydantic field (AgentRunResult / SimulationEnded)
_.coerce_string_to_list  # unused method — Pydantic field_validator
_.ensure_observations_present  # unused method — Pydantic model_validator
duration_seconds  # unused variable — Pydantic field (RunSummary / RunDetailResponse)
requirements  # unused variable — Pydantic field (SoftwareSpec)
impossible_requirement  # unused variable — Pydantic field (SoftwareSpec)
bg  # unused variable — Pydantic field (HexColor)
fg  # unused variable — Pydantic field (HexColor)
tool_arguments  # unused variable — Pydantic field (PdfDisplayEntry)
tool_result  # unused variable — Pydantic field (PdfDisplayEntry)
channel_color  # unused variable — Pydantic field (PdfDisplayEntry)
agent_role_name  # unused variable — Pydantic field (PdfTurnGroup)
agent_color  # unused variable — Pydantic field (PdfTurnGroup)
turns  # unused variable — Pydantic field (PdfRoundGroup)
export_run_pdf  # unused function — FastAPI route
