/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List all discovered simulation runs.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Get full detail for a specific simulation run.
         */
        get: operations["get_run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDetail
         * @description Full agent information for the run detail endpoint.
         */
        AgentDetail: {
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Tool Names */
            tool_names: string[];
            /** Model */
            model: string;
            /** System Prompt */
            system_prompt: string;
        };
        /**
         * EndReason
         * @description Why the simulation ended.
         * @enum {string}
         */
        EndReason: "scenario_complete" | "error";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health check endpoint.
         */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthStatus
         * @description Health check status values.
         * @enum {string}
         */
        HealthStatus: "ok";
        /**
         * MessageDetail
         * @description A single message with turn context for the run detail endpoint.
         */
        MessageDetail: {
            /** Message Id */
            message_id: string;
            /** Channel Id */
            channel_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Turn Number */
            turn_number: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * RunDetailResponse
         * @description Full detail of a simulation run including agents and messages.
         */
        RunDetailResponse: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Turns */
            total_turns: number;
            end_reason: components["schemas"]["EndReason"];
            /** Channel Ids */
            channel_ids: string[];
            /** Agents */
            agents: components["schemas"]["AgentDetail"][];
            /** Messages */
            messages: components["schemas"]["MessageDetail"][];
        };
        /**
         * RunListResponse
         * @description Response model for the list-all-runs endpoint.
         */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunSummary
         * @description Summary of a single simulation run for the runs list endpoint.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Turns */
            total_turns: number;
            end_reason: components["schemas"]["EndReason"];
            /** Has Evaluation */
            has_evaluation: boolean;
            /** Run Dir */
            run_dir: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
