/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List all discovered simulation runs.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Get full detail for a specific simulation run.
         */
        get: operations["get_run_detail_api_runs__scenario___run_dir_name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Stop the simulation if still running, then delete the run directory.
         */
        delete: operations["delete_run_api_runs__scenario___run_dir_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/eval-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Logs
         * @description Return the contents of the evaluation stdout log file.
         */
        get: operations["get_eval_logs_api_runs__scenario___run_dir_name__eval_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Stop a running simulation by sending SIGTERM to its process.
         */
        post: operations["stop_run_api_runs__scenario___run_dir_name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Evaluation
         * @description Launch an evaluation subprocess for a completed simulation run.
         *
         *     Validates that the run exists and is complete, that no evaluation is
         *     already in progress, and that the requested evaluators and provider
         *     are valid. Launches ``python -m schmidt evaluate`` as a detached
         *     background process.
         */
        post: operations["start_evaluation_api_runs__scenario___run_dir_name__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Stream simulation events as Server-Sent Events.
         *
         *     Only available for live simulations (detected via stream.json manifest).
         *     Proxies SSE from the simulation's embedded server. Returns 404 if the
         *     run is not found, and 409 if the simulation is not currently running.
         *
         *     The SSE ``data`` field of each frame contains a JSON object conforming to
         *     one of the SSEEvent union members, discriminated by the ``event_type`` field.
         */
        get: operations["stream_run_events_api_runs__scenario___run_dir_name__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Labels
         * @description Set labels for a simulation run, replacing any existing labels.
         */
        put: operations["update_labels_api_runs__scenario___run_dir_name__labels_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Note
         * @description Get the note content for a simulation run.
         */
        get: operations["get_note_api_runs__scenario___run_dir_name__note_get"];
        /**
         * Update Note
         * @description Set or update the note for a simulation run.
         */
        put: operations["update_note_api_runs__scenario___run_dir_name__note_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Labels
         * @description Get all unique labels across all simulation runs.
         */
        get: operations["list_all_labels_api_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fork Run
         * @description Create a forked simulation run from a specific message.
         *
         *     Clones the source run's git repository at the target message's commit,
         *     applies text edits to the JSONL, and launches the simulation as a
         *     background subprocess with ``--resume``.
         */
        post: operations["fork_run_api_runs__scenario___run_dir_name__fork_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Pdf
         * @description Export a simulation run as a formatted PDF document.
         *
         *     Generates a PDF containing messages, reasoning, and tool calls
         *     grouped by round and turn. Optionally filters to a single channel.
         */
        get: operations["export_run_pdf_api_runs__scenario___run_dir_name__export_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/export/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Artifacts
         * @description Export all artifacts from a simulation run as a zip archive.
         */
        get: operations["export_run_artifacts_api_runs__scenario___run_dir_name__export_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/export/artifacts/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Artifacts At Message
         * @description Export artifacts from a simulation run as they existed at a specific message.
         */
        get: operations["export_run_artifacts_at_message_api_runs__scenario___run_dir_name__export_artifacts__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{scenario}/{run_dir_name}/export/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Bundle
         * @description Export a simulation run as a tar.gz bundle including git history.
         */
        get: operations["export_run_bundle_api_runs__scenario___run_dir_name__export_bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Run Bundle
         * @description Import a simulation run from an exported bundle tar.gz.
         *
         *     Idempotent: if a run with the same run_id already exists, returns the
         *     existing run without re-importing.
         */
        post: operations["import_run_bundle_api_runs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description List all available scenarios with their knobs files and supported providers.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_name}/knobs/{knobs_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knobs Content
         * @description Read and return the contents of a knobs JSON file.
         */
        get: operations["get_knobs_content_api_scenarios__scenario_name__knobs__knobs_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_name}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Agent Roles
         * @description Return the agent IDs and display names for a scenario with the given knobs.
         */
        post: operations["get_agent_roles_api_scenarios__scenario_name__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Launch a new simulation as a background subprocess.
         */
        post: operations["start_run_api_runs_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Auth
         * @description Verify that the provided password is correct.
         *
         *     If the request reaches this endpoint, the middleware already validated
         *     the password. Returns authenticated=True unconditionally.
         */
        post: operations["verify_auth_api_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDetail
         * @description Full agent information for the run detail endpoint.
         */
        AgentDetail: {
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Tool Names */
            tool_names: string[];
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** System Prompt */
            system_prompt: string;
        };
        /**
         * AgentModelSummary
         * @description Per-agent model and provider info for run summary display.
         */
        AgentModelSummary: {
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
        };
        /**
         * AgentRoleInfo
         * @description Lightweight agent identity for the agent discovery endpoint.
         */
        AgentRoleInfo: {
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
        };
        /**
         * AgentRolesRequest
         * @description Request body for discovering agents in a scenario.
         */
        AgentRolesRequest: {
            /** Knobs */
            knobs: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AgentRolesResponse
         * @description Response listing agents that would participate in a scenario.
         */
        AgentRolesResponse: {
            /** Agents */
            agents: components["schemas"]["AgentRoleInfo"][];
        };
        /**
         * AllLabelsResponse
         * @description Response containing all unique labels across all runs.
         */
        AllLabelsResponse: {
            /** Labels */
            labels: string[];
        };
        /**
         * AuthVerifyResponse
         * @description Response model for the password verification endpoint.
         */
        AuthVerifyResponse: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** Body_import_run_bundle_api_runs_import_post */
        Body_import_run_bundle_api_runs_import_post: {
            /** File */
            file: string;
        };
        /**
         * ChannelMessage
         * @description A message sent by an agent to a channel.
         */
        ChannelMessage: {
            /** Message Id */
            message_id: string;
            /** Channel Id */
            channel_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Round Number */
            round_number: number;
            /** Token Count */
            token_count: number;
        };
        /**
         * DebugLogEntry
         * @description A single debug log entry from the simulation run.
         */
        DebugLogEntry: {
            /** Timestamp */
            timestamp: string;
            /** Logger Name */
            logger_name: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /**
         * EvalCostResponse
         * @description Evaluation cost summary for the run detail endpoint.
         */
        EvalCostResponse: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Input Tokens */
            cache_read_input_tokens: number;
            /** Cache Creation Input Tokens */
            cache_creation_input_tokens: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Model */
            model: string;
            /** Provider Name */
            provider_name: string;
        };
        /**
         * EvalLogLine
         * @description A single line from the evaluation stdout log.
         */
        EvalLogLine: {
            /** Line Number */
            line_number: number;
            /** Text */
            text: string;
        };
        /**
         * EvalLogsResponse
         * @description Response containing evaluation subprocess stdout/stderr output.
         */
        EvalLogsResponse: {
            /** Lines */
            lines: components["schemas"]["EvalLogLine"][];
        };
        /**
         * EvalMetricResponse
         * @description Result of a single evaluator for the run detail endpoint.
         */
        EvalMetricResponse: {
            /** Evaluator Name */
            evaluator_name: string;
            verdict: components["schemas"]["Verdict"];
            /** Score */
            score: number;
            /** Evidence */
            evidence: string[];
            /** Per Agent */
            per_agent: {
                [key: string]: components["schemas"]["Verdict"];
            };
        };
        /**
         * EvalReportResponse
         * @description Evaluation report for the run detail endpoint.
         */
        EvalReportResponse: {
            /** Metrics */
            metrics: components["schemas"]["EvalMetricResponse"][];
            evaluation_cost: components["schemas"]["EvalCostResponse"] | null;
        };
        /**
         * ForkRequest
         * @description Request body for creating a forked simulation run.
         */
        ForkRequest: {
            /** Target Message Id */
            target_message_id: string;
            /** Message Edits */
            message_edits: components["schemas"]["MessageEdit"][];
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Knobs */
            knobs: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ForkResponse
         * @description Response returned after a fork is created.
         */
        ForkResponse: {
            /** Fork Run Id */
            fork_run_id: string;
            /** Fork Run Dir */
            fork_run_dir: string;
        };
        /**
         * ForkSource
         * @description Provenance information for a forked simulation run.
         */
        ForkSource: {
            /** Source Run Id */
            source_run_id: string;
            /** Target Message Id */
            target_message_id: string;
            /**
             * Forked At
             * Format: date-time
             */
            forked_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health check endpoint.
         */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthStatus
         * @description Health check status values.
         * @enum {string}
         */
        HealthStatus: "ok";
        /**
         * ImportBundleResponse
         * @description Response after successfully importing a run bundle.
         */
        ImportBundleResponse: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Run Dir */
            run_dir: string;
        };
        /**
         * InternAnchor
         * @description Anchor for a timeline event in the Veyru intern-mode lifecycle.
         *
         *     Used for both the intern-join moment and the intern-takeover moment.
         *     ``target_message_id`` is the first ``MessageSent`` on the link channel
         *     after the anchor fired, so the frontend can scroll to that point.
         */
        InternAnchor: {
            /** Round Number */
            round_number: number;
            /** Target Message Id */
            target_message_id: string;
        };
        /**
         * KnobsContentResponse
         * @description Response containing the parsed contents of a knobs JSON file.
         */
        KnobsContentResponse: {
            /** Knobs */
            knobs: {
                [key: string]: unknown;
            };
        };
        /**
         * LaunchStatus
         * @description Status value for subprocess launch responses.
         * @enum {string}
         */
        LaunchStatus: "started";
        /**
         * MessageEdit
         * @description A single message text edit for a fork request.
         */
        MessageEdit: {
            /** Message Id */
            message_id: string;
            /** New Text */
            new_text: string;
        };
        /**
         * ModelInfo
         * @description A supported model prefix and its provider.
         */
        ModelInfo: {
            /** Model Prefix */
            model_prefix: string;
            /** Provider */
            provider: string;
        };
        /**
         * NoteResponse
         * @description Lightweight response for fetching a run's note content.
         */
        NoteResponse: {
            /** Content */
            content: string | null;
        };
        /**
         * ReasoningEntry
         * @description An LLM reasoning/thinking entry from an agent's turn.
         *
         *     ``channel_ids`` links this reasoning to the channels of the surrounding
         *     send_message calls from the same agent, so the frontend can show only
         *     reasoning relevant to the selected channel.
         */
        ReasoningEntry: {
            /** Message Id */
            message_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Round Number */
            round_number: number;
            /** Channel Ids */
            channel_ids: string[];
        };
        /**
         * RunDetailResponse
         * @description Full detail of a simulation run including agents, messages, and evaluation.
         */
        RunDetailResponse: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Messages */
            total_messages: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Duration Seconds */
            duration_seconds: number;
            status: components["schemas"]["RunStatus"];
            /** Channel Ids */
            channel_ids: string[];
            /** Provider */
            provider: string;
            /** Agents */
            agents: components["schemas"]["AgentDetail"][];
            /** Messages */
            messages: components["schemas"]["ChannelMessage"][];
            /** Reasoning */
            reasoning: components["schemas"]["ReasoningEntry"][];
            /** Tool Use */
            tool_use: components["schemas"]["ToolUseEntry"][];
            /** Debug Logs */
            debug_logs: components["schemas"]["DebugLogEntry"][];
            evaluation: components["schemas"]["EvalReportResponse"] | null;
            /** Evaluation In Progress */
            evaluation_in_progress: boolean;
            /** Has Eval Log File */
            has_eval_log_file: boolean;
            fork_source: components["schemas"]["ForkSource"] | null;
            swap_point: components["schemas"]["SwapPoint"] | null;
            intern_join: components["schemas"]["InternAnchor"] | null;
            intern_takeover: components["schemas"]["InternAnchor"] | null;
            /** Labels */
            labels: string[];
            /** Note */
            note: string | null;
        };
        /**
         * RunListResponse
         * @description Response model for the list-all-runs endpoint.
         */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunStatus
         * @description Status of a simulation run.
         * @enum {string}
         */
        RunStatus: "scenario_complete" | "in_progress" | "starting" | "error" | "killed";
        /**
         * RunSummary
         * @description Summary of a single simulation run for the runs list endpoint.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Messages */
            total_messages: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Duration Seconds */
            duration_seconds: number;
            status: components["schemas"]["RunStatus"];
            /** Has Evaluation */
            has_evaluation: boolean;
            /** Evaluation In Progress */
            evaluation_in_progress: boolean;
            /** Run Dir */
            run_dir: string;
            fork_source: components["schemas"]["ForkSource"] | null;
            /** Models */
            models: string[];
            /** Provider */
            provider: string;
            /** Agent Models */
            agent_models: components["schemas"]["AgentModelSummary"][];
            /** Labels */
            labels: string[];
            /** Has Note */
            has_note: boolean;
        };
        /**
         * SSEAgentConnected
         * @description SSE event emitted when an agent connects to the MCP server.
         */
        SSEAgentConnected: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent_connected";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
        };
        /**
         * SSEAgentCostUpdated
         * @description SSE event carrying an agent's cumulative cost after each run cycle.
         *
         *     Transient — not persisted to JSONL. The final total arrives in
         *     ``SSESimulationEnded``.
         */
        SSEAgentCostUpdated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent_cost_updated";
            /** Agent Id */
            agent_id: string;
            /** Cumulative Cost Usd */
            cumulative_cost_usd: number;
        };
        /**
         * SSEAgentRegistered
         * @description SSE event emitted when an agent joins the simulation.
         */
        SSEAgentRegistered: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent_registered";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** System Prompt */
            system_prompt: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Tool Names */
            tool_names: string[];
            /** Model */
            model: string;
            /** Provider */
            provider: string;
        };
        /**
         * SSEDebugLog
         * @description SSE event for a real-time debug log entry from the simulation process.
         */
        SSEDebugLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "debug_log";
            /** Timestamp */
            timestamp: string;
            /** Logger Name */
            logger_name: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /**
         * SSEInjectionDelivered
         * @description SSE event emitted when a scenario injection is pushed to an agent.
         */
        SSEInjectionDelivered: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "injection_delivered";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Round Number */
            round_number: number;
            /** Injection Text */
            injection_text: string;
        };
        /**
         * SSELLMResponseReceived
         * @description SSE event emitted when the LLM returns a response (reasoning text).
         */
        SSELLMResponseReceived: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "llm_response_received";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Text */
            text: string | null;
            /** Round Number */
            round_number: number;
        };
        /**
         * SSEMessageSent
         * @description SSE event emitted when an agent sends a message to a channel.
         */
        SSEMessageSent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "message_sent";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            message: components["schemas"]["SSESimulationMessagePayload"];
            /** Round Number */
            round_number: number;
            /** Token Count */
            token_count: number;
        };
        /**
         * SSERoundAdvanced
         * @description SSE event emitted when the game clock advances to a new round.
         */
        SSERoundAdvanced: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "round_advanced";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Round Number */
            round_number: number;
            /** Trigger */
            trigger: string;
        };
        /**
         * SSESimulationEnded
         * @description SSE event emitted once when the simulation finishes.
         */
        SSESimulationEnded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "simulation_ended";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            reason: components["schemas"]["RunStatus"];
            /** Total Messages */
            total_messages: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /**
         * SSESimulationMessagePayload
         * @description Nested message payload inside an SSE message_sent event.
         */
        SSESimulationMessagePayload: {
            /** Message Id */
            message_id: string;
            /** Channel Id */
            channel_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * SSESimulationStarted
         * @description SSE event emitted once when a simulation begins.
         */
        SSESimulationStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "simulation_started";
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
        };
        /**
         * SSEToolCallInvoked
         * @description SSE event emitted when an agent invokes a tool, before execution.
         */
        SSEToolCallInvoked: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "tool_call_invoked";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Call Id */
            call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Round Number */
            round_number: number;
        };
        /**
         * SSEToolResultReceived
         * @description SSE event emitted when a tool call completes and returns a result.
         */
        SSEToolResultReceived: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "tool_result_received";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Tool Name */
            tool_name: string;
            /** Call Id */
            call_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: string;
            /** Round Number */
            round_number: number;
        };
        /**
         * SSEVeyruStabilizationJudged
         * @description SSE event carrying the veyru stabilization judge's verdict for a stabilize_veyru call.
         */
        SSEVeyruStabilizationJudged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "veyru_stabilization_judged";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Round Number */
            round_number: number;
            /** Expected Actions */
            expected_actions: string;
            /** Judge Match */
            judge_match: boolean;
            /** Judge Explanation */
            judge_explanation: string;
        };
        /**
         * ScenarioInfo
         * @description Metadata about a single scenario, including its available knobs files.
         */
        ScenarioInfo: {
            /** Scenario Name */
            scenario_name: string;
            /** Knobs Files */
            knobs_files: string[];
            /** Available Evaluators */
            available_evaluators: string[];
        };
        /**
         * ScenariosResponse
         * @description Response listing all available scenarios, models, and providers.
         */
        ScenariosResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfo"][];
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Providers */
            providers: string[];
        };
        /**
         * StartEvaluationRequest
         * @description Request body for starting an evaluation on a completed run.
         */
        StartEvaluationRequest: {
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Evaluators */
            evaluators: string[];
        };
        /**
         * StartEvaluationResponse
         * @description Response after successfully launching an evaluation subprocess.
         */
        StartEvaluationResponse: {
            status: components["schemas"]["LaunchStatus"];
        };
        /**
         * StartRunRequest
         * @description Request body for starting a new simulation run.
         */
        StartRunRequest: {
            /** Scenario Name */
            scenario_name: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Knobs */
            knobs: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StartRunResponse
         * @description Response after successfully launching a new simulation.
         */
        StartRunResponse: {
            status: components["schemas"]["LaunchStatus"];
        };
        /**
         * SwapPoint
         * @description Anchor for the moment agents were swapped between teams.
         *
         *     ``target_message_id`` is the first ``MessageSent`` on a link channel
         *     after the swap fired, used by the frontend to scroll the timeline
         *     to that exact point. ``swapped_observer_display_names`` are the
         *     two observers who exchanged teams, in stable order.
         */
        SwapPoint: {
            /** Round Number */
            round_number: number;
            /** Target Message Id */
            target_message_id: string;
            /** Swapped Observer Display Names */
            swapped_observer_display_names: string[];
        };
        /**
         * ToolUseEntry
         * @description A scenario-specific tool invocation with its result.
         *
         *     Each entry represents one tool call made by an agent. The ``result``
         *     field is filled once the tool execution completes. ``timestamp``
         *     anchors to ``tool_call_invoked``; ``result_timestamp`` anchors to
         *     ``tool_result_received`` so the UI can render call and result at
         *     their true chronological positions.
         */
        ToolUseEntry: {
            /** Message Id */
            message_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Tool Name */
            tool_name: string;
            /** Call Id */
            call_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Result Timestamp */
            result_timestamp: string | null;
            /** Round Number */
            round_number: number;
            stabilize_metadata?: components["schemas"]["VeyruStabilizeMetadata"] | null;
        };
        /**
         * UpdateLabelsRequest
         * @description Request body for setting labels on a run.
         */
        UpdateLabelsRequest: {
            /** Labels */
            labels: string[];
        };
        /**
         * UpdateLabelsResponse
         * @description Response after updating labels on a run.
         */
        UpdateLabelsResponse: {
            /** Labels */
            labels: string[];
        };
        /**
         * UpdateNoteRequest
         * @description Request body for setting or updating a note on a run.
         */
        UpdateNoteRequest: {
            /** Content */
            content: string;
        };
        /**
         * UpdateNoteResponse
         * @description Response after updating a note on a run.
         */
        UpdateNoteResponse: {
            /** Content */
            content: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description Three-valued outcome for a single evaluation metric.
         * @enum {string}
         */
        Verdict: "pass" | "fail" | "partial";
        /**
         * VeyruStabilizeMetadata
         * @description Judge context captured for a single ``stabilize_veyru`` call.
         *
         *     Attached to the corresponding ``ToolUseEntry`` so the frontend can show
         *     the expected procedure and the LLM judge's verdict alongside the raw
         *     tool call. Present only on ``stabilize_veyru`` entries.
         */
        VeyruStabilizeMetadata: {
            /** Expected Actions */
            expected_actions: string;
            /** Judge Match */
            judge_match: boolean;
            /** Judge Explanation */
            judge_explanation: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    get_run_detail_api_runs__scenario___run_dir_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__scenario___run_dir_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_logs_api_runs__scenario___run_dir_name__eval_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__scenario___run_dir_name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_evaluation_api_runs__scenario___run_dir_name__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_runs__scenario___run_dir_name__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream. Each SSE frame has an `event` field matching the event_type discriminator and a `data` field containing the JSON payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SSESimulationStarted"] | components["schemas"]["SSEAgentRegistered"] | components["schemas"]["SSEAgentConnected"] | components["schemas"]["SSEMessageSent"] | components["schemas"]["SSELLMResponseReceived"] | components["schemas"]["SSEToolCallInvoked"] | components["schemas"]["SSEToolResultReceived"] | components["schemas"]["SSERoundAdvanced"] | components["schemas"]["SSEInjectionDelivered"] | components["schemas"]["SSESimulationEnded"] | components["schemas"]["SSEAgentCostUpdated"] | components["schemas"]["SSEDebugLog"] | components["schemas"]["SSEVeyruStabilizationJudged"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_labels_api_runs__scenario___run_dir_name__labels_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateLabelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_api_runs__scenario___run_dir_name__note_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_runs__scenario___run_dir_name__note_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateNoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_labels_api_labels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllLabelsResponse"];
                };
            };
        };
    };
    fork_run_api_runs__scenario___run_dir_name__fork_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_pdf_api_runs__scenario___run_dir_name__export_pdf_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
            };
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF document of the simulation run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_artifacts_api_runs__scenario___run_dir_name__export_artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip archive of the simulation run artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_artifacts_at_message_api_runs__scenario___run_dir_name__export_artifacts__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip archive of artifacts at a specific message commit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_bundle_api_runs__scenario___run_dir_name__export_bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
                run_dir_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tar.gz bundle of the simulation run with git history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/gzip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_run_bundle_api_runs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_run_bundle_api_runs_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBundleResponse"];
                };
            };
            /** @description Invalid or incomplete bundle. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
        };
    };
    get_knobs_content_api_scenarios__scenario_name__knobs__knobs_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_name: string;
                knobs_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnobsContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_roles_api_scenarios__scenario_name__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRolesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRolesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    verify_auth_api_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthVerifyResponse"];
                };
            };
        };
    };
}
