/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List all discovered simulation runs.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Get full detail for a specific simulation run.
         */
        get: operations["get_run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Delete a simulation run and all its files.
         */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Stop a running simulation by sending SIGTERM to its process.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Stream simulation events as Server-Sent Events.
         *
         *     Only available for live simulations (detected via stream.json manifest).
         *     Proxies SSE from the simulation's embedded server. Returns 404 if the
         *     run is not found, and 409 if the simulation is not currently running.
         *
         *     The SSE ``data`` field of each frame contains a JSON object conforming to
         *     one of the SSEEvent union members, discriminated by the ``event_type`` field.
         */
        get: operations["stream_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fork Run
         * @description Create a forked simulation run from a specific message.
         *
         *     Truncates the source event log at the target message, applies text edits,
         *     writes the result to a new run directory, and launches the simulation as
         *     a background subprocess.
         */
        post: operations["fork_run_api_runs__run_id__fork_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDetail
         * @description Full agent information for the run detail endpoint.
         */
        AgentDetail: {
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Tool Names */
            tool_names: string[];
            /** Model */
            model: string;
            /** System Prompt */
            system_prompt: string;
        };
        /**
         * ChannelMessage
         * @description A message sent by an agent to a channel.
         */
        ChannelMessage: {
            /** Message Id */
            message_id: string;
            /** Channel Id */
            channel_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Turn Number */
            turn_number: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * DebugLogEntry
         * @description A single debug log entry from the simulation run.
         */
        DebugLogEntry: {
            /** Timestamp */
            timestamp: string;
            /** Logger Name */
            logger_name: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /**
         * EvalMetricResponse
         * @description Result of a single evaluator for the run detail endpoint.
         */
        EvalMetricResponse: {
            /** Evaluator Name */
            evaluator_name: string;
            verdict: components["schemas"]["Verdict"];
            /** Score */
            score: number;
            /** Evidence */
            evidence: string[];
            /** Per Agent */
            per_agent: {
                [key: string]: components["schemas"]["Verdict"];
            };
        };
        /**
         * EvalReportResponse
         * @description Evaluation report for the run detail endpoint.
         */
        EvalReportResponse: {
            /** Metrics */
            metrics: components["schemas"]["EvalMetricResponse"][];
        };
        /**
         * ForkRequest
         * @description Request body for creating a forked simulation run.
         */
        ForkRequest: {
            /** Target Message Id */
            target_message_id: string;
            /** Message Edits */
            message_edits: components["schemas"]["MessageEdit"][];
            /** Model */
            model: string;
        };
        /**
         * ForkResponse
         * @description Response returned after a fork is created.
         */
        ForkResponse: {
            /** Fork Run Id */
            fork_run_id: string;
            /** Fork Run Dir */
            fork_run_dir: string;
        };
        /**
         * ForkSource
         * @description Provenance information for a forked simulation run.
         */
        ForkSource: {
            /** Source Run Id */
            source_run_id: string;
            /** Target Message Id */
            target_message_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health check endpoint.
         */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthStatus
         * @description Health check status values.
         * @enum {string}
         */
        HealthStatus: "ok";
        /**
         * MessageEdit
         * @description A single message text edit for a fork request.
         */
        MessageEdit: {
            /** Message Id */
            message_id: string;
            /** New Text */
            new_text: string;
        };
        /**
         * ReasoningEntry
         * @description An LLM reasoning/thinking entry from an agent's turn.
         *
         *     ``channel_ids`` links this reasoning to the channels of the surrounding
         *     send_message calls from the same agent, so the frontend can show only
         *     reasoning relevant to the selected channel.
         */
        ReasoningEntry: {
            /** Message Id */
            message_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Turn Number */
            turn_number: number;
            /** Round Number */
            round_number: number;
            /** Channel Ids */
            channel_ids: string[];
        };
        /**
         * RunDetailResponse
         * @description Full detail of a simulation run including agents, messages, and evaluation.
         */
        RunDetailResponse: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Messages */
            total_messages: number;
            status: components["schemas"]["RunStatus"];
            /** Channel Ids */
            channel_ids: string[];
            /** Agents */
            agents: components["schemas"]["AgentDetail"][];
            /** Messages */
            messages: components["schemas"]["ChannelMessage"][];
            /** Reasoning */
            reasoning: components["schemas"]["ReasoningEntry"][];
            /** Tool Use */
            tool_use: components["schemas"]["ToolUseEntry"][];
            /** Debug Logs */
            debug_logs: components["schemas"]["DebugLogEntry"][];
            evaluation: components["schemas"]["EvalReportResponse"] | null;
            fork_source: components["schemas"]["ForkSource"] | null;
        };
        /**
         * RunListResponse
         * @description Response model for the list-all-runs endpoint.
         */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunStatus
         * @description Why the simulation ended.
         * @enum {string}
         */
        RunStatus: "scenario_complete" | "in_progress" | "error";
        /**
         * RunSummary
         * @description Summary of a single simulation run for the runs list endpoint.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Messages */
            total_messages: number;
            status: components["schemas"]["RunStatus"];
            /** Has Evaluation */
            has_evaluation: boolean;
            /** Run Dir */
            run_dir: string;
            fork_source: components["schemas"]["ForkSource"] | null;
        };
        /**
         * SSEAgentConnected
         * @description SSE event emitted when an agent connects to the MCP server.
         */
        SSEAgentConnected: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent_connected";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
        };
        /**
         * SSEAgentRegistered
         * @description SSE event emitted when an agent joins the simulation.
         */
        SSEAgentRegistered: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent_registered";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Role Name */
            role_name: string;
            /** System Prompt */
            system_prompt: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Tool Names */
            tool_names: string[];
            /** Model */
            model: string;
        };
        /**
         * SSEDebugLog
         * @description SSE event for a real-time debug log entry from the simulation process.
         */
        SSEDebugLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "debug_log";
            /** Timestamp */
            timestamp: string;
            /** Logger Name */
            logger_name: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /**
         * SSEInjectionDelivered
         * @description SSE event emitted when a scenario injection is pushed to an agent.
         */
        SSEInjectionDelivered: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "injection_delivered";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Round Number */
            round_number: number;
            /** Injection Text */
            injection_text: string;
        };
        /**
         * SSELLMResponseReceived
         * @description SSE event emitted when the LLM returns a response (reasoning text).
         */
        SSELLMResponseReceived: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "llm_response_received";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Text */
            text: string | null;
        };
        /**
         * SSEMessagePreview
         * @description SSE event for in-progress send_message text preview.
         *
         *     Transient — not persisted to JSONL. The complete message arrives in a
         *     subsequent SSEMessageSent event.
         */
        SSEMessagePreview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "message_preview";
            /** Agent Id */
            agent_id: string;
            /** Channel Id */
            channel_id: string;
            /** Text */
            text: string;
            /** Is Final */
            is_final: boolean;
        };
        /**
         * SSEMessageSent
         * @description SSE event emitted when an agent sends a message to a channel.
         */
        SSEMessageSent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "message_sent";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            message: components["schemas"]["SSESimulationMessagePayload"];
        };
        /**
         * SSERoundAdvanced
         * @description SSE event emitted when the game clock advances to a new round.
         */
        SSERoundAdvanced: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "round_advanced";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Round Number */
            round_number: number;
            /** Trigger */
            trigger: string;
        };
        /**
         * SSESimulationEnded
         * @description SSE event emitted once when the simulation finishes.
         */
        SSESimulationEnded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "simulation_ended";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            reason: components["schemas"]["RunStatus"];
            /** Total Messages */
            total_messages: number;
        };
        /**
         * SSESimulationMessagePayload
         * @description Nested message payload inside an SSE message_sent event.
         */
        SSESimulationMessagePayload: {
            /** Message Id */
            message_id: string;
            /** Channel Id */
            channel_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * SSESimulationStarted
         * @description SSE event emitted once when a simulation begins.
         */
        SSESimulationStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "simulation_started";
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Description */
            scenario_description: string;
            /** Channel Ids */
            channel_ids: string[];
            /** Scenario Config */
            scenario_config: {
                [key: string]: unknown;
            };
        };
        /**
         * SSETokenDelta
         * @description SSE event emitted token-by-token during LLM response streaming.
         *
         *     Transient — not persisted to JSONL. The complete text arrives in a
         *     subsequent SSELLMResponseReceived event.
         */
        SSETokenDelta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "token_delta";
            /** Agent Id */
            agent_id: string;
            /** Text */
            text: string;
            /** Is Final */
            is_final: boolean;
        };
        /**
         * SSEToolResultReceived
         * @description SSE event emitted when a tool call completes and returns a result.
         */
        SSEToolResultReceived: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "tool_result_received";
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Agent Id */
            agent_id: string;
            /** Tool Name */
            tool_name: string;
            /** Call Id */
            call_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: string;
        };
        /**
         * ToolUseEntry
         * @description A scenario-specific tool invocation with its result.
         *
         *     Each entry represents one tool call made by an agent. The ``result``
         *     field is filled once the tool execution completes.
         */
        ToolUseEntry: {
            /** Message Id */
            message_id: string;
            /** Sender Agent Id */
            sender_agent_id: string;
            /** Tool Name */
            tool_name: string;
            /** Call Id */
            call_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Turn Number */
            turn_number: number;
            /** Round Number */
            round_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description Three-valued outcome for a single evaluation metric.
         * @enum {string}
         */
        Verdict: "pass" | "fail" | "partial";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream. Each SSE frame has an `event` field matching the event_type discriminator and a `data` field containing the JSON payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SSESimulationStarted"] | components["schemas"]["SSEAgentRegistered"] | components["schemas"]["SSEAgentConnected"] | components["schemas"]["SSEMessageSent"] | components["schemas"]["SSELLMResponseReceived"] | components["schemas"]["SSEToolResultReceived"] | components["schemas"]["SSERoundAdvanced"] | components["schemas"]["SSEInjectionDelivered"] | components["schemas"]["SSESimulationEnded"] | components["schemas"]["SSETokenDelta"] | components["schemas"]["SSEMessagePreview"] | components["schemas"]["SSEDebugLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fork_run_api_runs__run_id__fork_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
