"""Regenerate ``vulture_whitelist.py`` from what vulture currently reports.

Backs ``make vulture-whitelist``. Vulture's own ``--make-whitelist`` emits one bare
name per line, and a bare name is an expression statement with no effect, so the
CodeQL ``code-quality`` suite reports every line of the result under
``py/ineffectual-statement``. That check is configured outside this repository, so
the shape of the file is the only side available to change.

Vulture reads a whitelist by parsing it and recording which names are loaded, never
by running it, so any expression that mentions the names does the same job. This
writes them as a single tuple, which loads all of them and is not a statement with
no effect.
"""

import re
import subprocess
import sys
from pathlib import Path

# The paths `make lint-server` and `make check-server` hand to vulture. Generating
# over a narrower set drops the entries covering whatever it left out.
SCANNED_PATHS = ("src/", "scripts/", "linter/")
MIN_CONFIDENCE = "60"
WHITELIST_PATH = Path("vulture_whitelist.py")

# Vulture exits 3 when it found dead code and 0 when it found none. Both are normal
# here: the second only means the whitelist is empty.
_EXPECTED_EXIT_CODES = frozenset({0, 3})

_ENTRY = re.compile(r"^(?P<name>[A-Za-z_][A-Za-z_0-9.]*)(?P<comment>\s*#.*)?$")

_HEADER = '''"""Names vulture reports as unused that are reached from somewhere it cannot see.

Generated by ``make vulture-whitelist``. Do not edit by hand: the next regeneration
overwrites it.

A tuple rather than one bare name per line, because a bare name is an expression
statement with no effect and the CodeQL ``code-quality`` suite reports every one of
them. Vulture parses this file and records the names it loads, so a tuple whitelists
them exactly as the bare-name form did.

The name has to start with an underscore. Vulture scans this file along with the
rest, and would otherwise report the variable holding the whitelist as unused.
"""

_WHITELIST = (
'''


def collect_findings() -> str:
    """Return vulture's ``--make-whitelist`` output for the scanned paths."""
    completed = subprocess.run(
        args=[
            sys.executable,
            "-m",
            "vulture",
            *SCANNED_PATHS,
            "--min-confidence",
            MIN_CONFIDENCE,
            "--make-whitelist",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode not in _EXPECTED_EXIT_CODES:
        raise SystemExit(
            f"vulture exited {completed.returncode}, which is neither 0 (nothing "
            f"found) nor 3 (findings):\n{completed.stderr}"
        )
    return completed.stdout


def reshape(findings: str) -> str:
    """Turn one-name-per-line output into the tuple assignment written to disk."""
    entries: list[str] = []
    for raw in findings.splitlines():
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        match = _ENTRY.match(raw.rstrip())
        if match is None:
            raise SystemExit(
                f"vulture emitted a line this script cannot read: {raw!r}. Its "
                "whitelist format changed, so this script needs updating."
            )
        comment = match.group("comment")
        if comment is None:
            comment = ""
        entries.append(f"    {match.group('name')},{comment}")
    return _HEADER + "\n".join(entries) + "\n)\n"


def main() -> None:
    """Write the regenerated whitelist and report how many names it covers."""
    findings = collect_findings()
    content = reshape(findings=findings)
    WHITELIST_PATH.write_text(content)
    covered = len([line for line in findings.splitlines() if line.strip()])
    print(f"Wrote {WHITELIST_PATH} covering {covered} name(s)")


if __name__ == "__main__":
    main()
