"""Word lists for the telephone scenario.

A pool of common English words is shuffled with a fixed seed and dealt into
40 round lists whose sizes cycle uniformly from 5 to 16 items. No word
appears in more than one list.
"""

import random
from typing import NamedTuple


class WordList(NamedTuple):
    """A word list assigned to a single round of the telephone game."""

    round_number: int
    items: list[str]


# Pool of 420+ common, concrete English nouns — easy to visualize, unambiguous.
# Must contain at least 404 words (sum of sizes 5..16 cycled over 40 rounds).
WORD_POOL: list[str] = [
    # A
    "acorn",
    "admiral",
    "albatross",
    "almond",
    "anchor",
    "antelope",
    "antler",
    "anvil",
    "apple",
    "apricot",
    "armadillo",
    "armchair",
    "arrow",
    "artichoke",
    "atlas",
    "avocado",
    "axle",
    # B
    "badge",
    "badger",
    "balloon",
    "bamboo",
    "banjo",
    "barnacle",
    "barrel",
    "basket",
    "beacon",
    "beetle",
    "biscuit",
    "blanket",
    "blossom",
    "bluebird",
    "bobcat",
    "bonfire",
    "bookshelf",
    "boulder",
    "bramble",
    "brimstone",
    "broom",
    "bucket",
    "bugle",
    "bullfrog",
    "bunker",
    "butterfly",
    "button",
    # C
    "cabin",
    "cactus",
    "camel",
    "candle",
    "cannon",
    "canyon",
    "carpet",
    "carrot",
    "castle",
    "caterpillar",
    "cauldron",
    "cellar",
    "chariot",
    "cherry",
    "chestnut",
    "chimney",
    "chisel",
    "cinnamon",
    "clover",
    "cobalt",
    "cobweb",
    "coconut",
    "compass",
    "condor",
    "coral",
    "cormorant",
    "cradle",
    "cricket",
    "crocodile",
    "crossbow",
    "crystal",
    "curtain",
    "cypress",
    # D
    "dagger",
    "dandelion",
    "diamond",
    "dinosaur",
    "dolphin",
    "donkey",
    "doorbell",
    "dormouse",
    "dragonfly",
    "drumstick",
    "dungeon",
    "dustpan",
    # E
    "eagle",
    "earring",
    "easel",
    "eggplant",
    "elephant",
    "ember",
    "emerald",
    "envelope",
    "ermine",
    # F
    "falcon",
    "feather",
    "fiddler",
    "fig",
    "finch",
    "firefly",
    "flamingo",
    "flintlock",
    "flounder",
    "fortress",
    "fossil",
    "fountain",
    "foxglove",
    "furnace",
    # G
    "garlic",
    "garnet",
    "gazelle",
    "gerbil",
    "giraffe",
    "glacier",
    "goblet",
    "goldfinch",
    "gondola",
    "gooseberry",
    "gorilla",
    "grapevine",
    "grasshopper",
    "gravel",
    "grenade",
    "grizzly",
    "guitar",
    "gutter",
    # H
    "hammock",
    "hamster",
    "harpoon",
    "harpsichord",
    "haystack",
    "hedgehog",
    "helmet",
    "heron",
    "hibiscus",
    "horizon",
    "hornet",
    "horseshoe",
    "hourglass",
    "hummingbird",
    # I
    "ibex",
    "iceberg",
    "igloo",
    "iguana",
    "inkwell",
    "ivory",
    # J
    "jackal",
    "jackrabbit",
    "jaguar",
    "javelin",
    "jellyfish",
    "journal",
    "juniper",
    # K
    "kangaroo",
    "kayak",
    "kennel",
    "ketchup",
    "kettle",
    "kingfisher",
    "knapsack",
    "koala",
    # L
    "labyrinth",
    "ladder",
    "ladybug",
    "lantern",
    "lemon",
    "lemur",
    "leopard",
    "lighthouse",
    "lizard",
    "lobster",
    "locket",
    "locust",
    "lynx",
    # M
    "mackerel",
    "magnet",
    "mammoth",
    "mandolin",
    "mantis",
    "maple",
    "marble",
    "marigold",
    "meadow",
    "meerkat",
    "mirror",
    "mitten",
    "monocle",
    "mongoose",
    "mosquito",
    "mushroom",
    "mustard",
    # N
    "napkin",
    "narwhal",
    "nectar",
    "necklace",
    "newt",
    "nightingale",
    "nutmeg",
    # O
    "obelisk",
    "obsidian",
    "octopus",
    "olive",
    "onion",
    "opal",
    "orchid",
    "osprey",
    "ostrich",
    "otter",
    "overcoat",
    "oyster",
    # P
    "palette",
    "panther",
    "parachute",
    "parsley",
    "parsnip",
    "partridge",
    "peacock",
    "pebble",
    "pelican",
    "penguin",
    "pepper",
    "pheasant",
    "pickaxe",
    "pillow",
    "pineapple",
    "piranha",
    "platypus",
    "plumber",
    "pomegranate",
    "porcupine",
    "pretzel",
    "prism",
    "puffin",
    "pumpkin",
    "pyramid",
    # Q
    "quarry",
    "quartz",
    "quiver",
    # R
    "rabbit",
    "raccoon",
    "radish",
    "raisin",
    "ratchet",
    "raven",
    "reindeer",
    "rhinoceros",
    "riddle",
    "robin",
    "rocket",
    "rosemary",
    "rudder",
    # S
    "saddle",
    "saffron",
    "salamander",
    "salmon",
    "sandcastle",
    "sapphire",
    "satchel",
    "scarecrow",
    "scepter",
    "schooner",
    "scorpion",
    "seagull",
    "seahorse",
    "shamrock",
    "skeleton",
    "sparrow",
    "sphinx",
    "spinach",
    "spyglass",
    "squirrel",
    "stallion",
    "starfish",
    "stingray",
    "stork",
    "sundial",
    "sunflower",
    "swallow",
    "swordfish",
    # T
    "tambourine",
    "tangerine",
    "tapestry",
    "telescope",
    "termite",
    "thimble",
    "thistle",
    "timber",
    "tornado",
    "tortoise",
    "toucan",
    "trident",
    "trumpet",
    "tulip",
    "turret",
    "turtle",
    # U
    "umbrella",
    "unicorn",
    "urchin",
    # V
    "vanilla",
    "venom",
    "velvet",
    "viper",
    "violin",
    "volcano",
    "vulture",
    # W
    "waffle",
    "walnut",
    "walrus",
    "warbler",
    "warthog",
    "waterfall",
    "weasel",
    "whirlpool",
    "willow",
    "windmill",
    "wolverine",
    "wombat",
    "woodpecker",
    # X
    "xylophone",
    # Y
    "yak",
    "yardstick",
    # Z
    "zebra",
    "zeppelin",
    "zinnia",
    # --- extra words to fill pool ---
    "accordion",
    "asparagus",
    "barnyard",
    "basilisk",
    "binoculars",
    "blackbird",
    "blueberry",
    "boomerang",
    "bracelet",
    "broccoli",
    "buckwheat",
    "bulldozer",
    "candelabra",
    "cardboard",
    "carousel",
    "catamaran",
    "centipede",
    "chandelier",
    "corkscrew",
    "cranberry",
    "dalmatian",
    "dirigible",
    "doorstep",
    "dumbbell",
    "earthworm",
    "eyelash",
    "fishbowl",
    "flagpole",
    "footprint",
    "frostbite",
    "gadget",
    "gallstone",
    "gingerbread",
    "groundhog",
    "harmonica",
    "hazelnut",
    "holster",
    "honeybee",
    "hurricane",
    "jackknife",
    "jukebox",
    "kaleidoscope",
    "kettledrum",
    "lamppost",
    "laundry",
    "lawnmower",
    "licorice",
    "limestone",
    "mandarin",
    "maypole",
    "milkshake",
    "mockingbird",
    "moonstone",
    "moustache",
    "nectarine",
    "nighthawk",
    "oatmeal",
    "orangutan",
    "parakeet",
    "pendulum",
    "periscope",
    "pitchfork",
    "portrait",
    "quicksand",
    "raspberry",
    "sailboat",
    "sandpiper",
    "saxophone",
    "slingshot",
    "snowflake",
    "stopwatch",
    "suitcase",
    "terrarium",
    "toadstool",
    "tombstone",
    "trapezoid",
    "tumbleweed",
    "turquoise",
    "vineyard",
    "whippoorwill",
    "zucchini",
    "alligator",
    "blunderbuss",
    "chinchilla",
    "dragonboat",
    "eucalyptus",
    "fisherman",
    "guacamole",
    "handkerchief",
    "jellybean",
    "limousine",
    "marshmallow",
    "nightcrawler",
    "peppermint",
    "rattlesnake",
    "silverware",
    "thumbtack",
    "wallpaper",
    "windshield",
    "yellowtail",
    "cantaloupe",
    "cauliflower",
]

# Sizes cycle 7..15 across 40 rounds.
_ROUND_SIZES: list[int] = [7 + (i % 9) for i in range(40)]

# Total words needed across all 40 rounds.
_TOTAL_WORDS_NEEDED: int = sum(_ROUND_SIZES)


def get_word_lists(seed: int) -> list[WordList]:
    """Generate 40 word lists by shuffling the pool with a fixed seed.

    Sizes cycle 7-15. The pool is shuffled once, then words are dealt
    sequentially into each round's list. A second shuffle randomizes
    the round order so list sizes are unpredictable.
    """
    if len(WORD_POOL) < _TOTAL_WORDS_NEEDED:
        raise ValueError(
            f"Word pool has {len(WORD_POOL)} words but {_TOTAL_WORDS_NEEDED} are needed"
        )

    rng = random.Random(seed)
    pool = list(WORD_POOL)
    rng.shuffle(pool)

    # Deal words into lists of cycling sizes.
    lists: list[WordList] = []
    offset = 0
    for i, size in enumerate(_ROUND_SIZES):
        lists.append(
            WordList(
                round_number=i + 1,
                items=pool[offset : offset + size],
            )
        )
        offset += size

    # Shuffle round order so sizes are unpredictable, then renumber.
    rng.shuffle(lists)
    return [WordList(round_number=pos + 1, items=wl.items) for pos, wl in enumerate(lists)]
